---
- name: Copy executable jar
  copy:
    src: ../files/demo.jar
    dest: "{{app_jar}}"
    owner: "{{deploy_user}}"
    group: "{{deploy_group}}"
    mode: 0770
  register: jar_copy

- name: Install myapp.service systemd unit file
  template:
    src: "templates/systemd.service.j2"
    dest: "/etc/systemd/system/{{app}}.service"

- name: Make sure a service is running
  systemd: state=started name={{app}}

- name: Restart myapp.service
  systemd:
    state: started
    name: myapp
  when: jar_copy.changed
  notify:
    - reload systemd

- name: Wait for the HTTP port to be listening
  wait_for:
    port: 8080
    timeout: "{{ startup_timeout | default('60') | int }}"
