---
- name: Copy executable jar
  copy:
    src: ../files/demo.jar
    dest: "{{app_jar}}"
    owner: "{{deploy_user}}"
    group: "{{deploy_group}}"
    mode: 0770
  register: jar_copy

- name: Install myapp.service systemd unit file
  template:
    src: "templates/systemd.service.j2"
    dest: "/etc/systemd/system/{{app}}.service"
    mode: 755
  register: service_file

- name: Restart {{app}}.service
  systemd:
    state: started
    name: {{app}}
  when: service_file.changed or jar_copy.changed
  notify:
    - reload systemd

- name: Wait for the HTTP port to be listening
  wait_for:
    port: 8080
    timeout: "{{ startup_timeout | default('60') | int }}"
