---
# tasks file for java
# - name: add repo for java 8
#   apt_repository:
#     repo: 'ppa:openjdk-r/ppa'
#     state: present

- name: install java {{jdk_version}}
  apt:
    name: openjdk-{{jdk_version}}-jdk
    state: present
    update-cache: no
    force: no
