---
- hosts: masters
  remote_user: root
  become: true
  vars_files:
      - vars/main.yml
  roles:
  # - ANXS.postgresql
   - apache2-reverse-proxy

- hosts: slaves
  become: true

  roles:
   - java
   - app-conf
   - standalone-webapp
