- name: "Déploiement DataBase+Load Balancer"
  hosts: masters
  #remote_user: root
  become: true
  # vars_files:
      # - vars/main.yml
  roles:
  #  - ANXS.postgresql
   - geerlingguy.postgresql
   - apache2-reverse-proxy

# - name: Déploiement avec Rôles
#   hosts: slave1
#   become: true

#   roles:
#    - role: prepare
#    - role: app-conf
#      conf_files:
#        - "templates/{{app}}/application.properties.j2"
#      # - "templates/{{app}}/application_additional.properties.j2"
#    - {role: standalone-webapp-java, jdk_version: 8}

#   # alternative syntax
#   #  - role: standalone-webapp-java
#   #    jdk_version: 8
