---
- hosts: masters
  remote_user: root
  become: true
  vars_files:
      - vars/main.yml
  roles:
   - ANXS.postgresql

- hosts: slaves
  become: true

  roles:
   - java
   - app-conf
   - standalone-webapp
