- name: "Déploiement DataBase+Load Balancer"
  hosts: masters
  become: true

  roles:

   - geerlingguy.postgresql
   - apache2-reverse-proxy

  post_tasks:

  - postgresql_schema:
      name: personne
      database: coding_dojo
      login_user: postgres
      login_password: postgres
      login_host: 192.168.61.10
      owner: postgres
      state: present

- name: Déploiement application
  hosts: slaves
  become: true

  roles:

   - role: prepare
   - role: app-conf
     conf_files:
       - "templates/{{app}}/application.properties.j2"
   - {role: standalone-webapp-java, jdk_version: 8}
