---
# tasks file for java
- name: add repo for java 8
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'
    state: present

- name: install java 8
  apt:
    name: openjdk-8-jdk
    state: present
    update-cache: no
    force: no
