---
# tasks file for standalone-webapp
- name: Copy executable jar
  copy:
    src: ../demo/target/demo.jar
    dest: "{{app_jar}}"
    owner: "{{deploy_user}}"
    group: "{{deploy_group}}"
    mode: 0770
  register: jar_copy

- name: Install myapp.service systemd unit file
  template:
    rc: "templates/systemd.service.j2"
    dest: "/etc/systemd/system/{{app}}.service"

- name: Install external application.properties
  template:
    src: "templates/application.properties.j2"
    dest: "{{conf_dir}}/application.properties"

- name: (re)Start myapp.service
  systemd:
    state: "restarted"
    name: "myapp.service"
    daemon_reload: "yes"
  when: True or jar_copy.changed

- name: Wait for the HTTP port to be listening
  wait_for:
    port: 8080
    timeout: 10
