---
- name: Make sure Apache is installed
  apt: pkg={{item}} update_cache=yes state=latest
  with_items:
    - apache2

- name: Make sure needed modules are present
  apache2_module: name={{ item }} state=present
  with_items: "{{ balancer_apache_modules }}"
  notify:
    - restart apache

- name: Make sure balancer virtual host configuration file is up to date
  template:
    src=templates/src.j2
    dest=/etc/apache2/conf-available/{{ balancer_config_file_name }}.conf
    mode=0644

- name: Make sure balancer virtual host configuration is enabled
  command:
    a2enconf {{ item }}.conf
    creates=/etc/apache2/conf-enabled/{{ item }}.conf
  with_items:
    - "{{ balancer_config_file_name }}"
  notify:
    - restart apache
