---
# tasks file for apache2-reverse-proxy
- name: Install Apache
  block:
    - apt: name={{ item }} state=installed update_cache=yes
      with_items:
       - apache2
    - template: src=templates/src.j2 dest=/etc/foo.conf
  #  - service: name=bar state=started enabled=True
  become: true
  become_user: root
